version: '3.4'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
      # args:
      #   API_HOST: https://neorion.koslib.dev.intelligems.eu
      #   API_NAMESPACE: api/v1
    image: neorion-dashboard:local
    volumes:
      - ./public:/usr/src/app/public/
      - ./src:/usr/src/app/src/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

